name: Test install

on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:

    runs-on: windows-11-arm
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: ARM64
      
      - name: Install all
        run: |
          vcpkg install proj

      - name: Upload Vcpkg Packages as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-packages
          path: c:\vcpkg\packages
        
      - name: Upload Vcpkg Installed as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-installed
          path: c:\vcpkg\installed
          
